### ISSUE TITLE
Accidental unexpected parameters after the name results in potentially confusing exception

### ISSUE THREAD

**Issue by natlv** [AY2425S1-CS2103T-T16-4/tp#186]
Accidentally including unexpected parameters after the name results in the error message "Names should only contain..."

An example of this is in the following command: adda n/Ansel Chong tg/T02 sn/A0298704B a/Assignment 1 d/2023-11-29

Here, the tutorial group parameter, tg, is not expected. However, the user would be unlikely to figure out that this is the issue especially if it is his first time, and may not know how to continue with the given error message.

**Comment by natlv** [comment]
If I remember correctly, the original AddressBook has a similar issue. So might not need to come with a direct fix for this.

**Comment by Ansel-Ch** [comment]
It's cause of how the AddAssignment Parser works. It does not scan for the tutorial group prefix, so basically the string passed into the parseName method will be "Ansel Chong tg/T02 " which does not match the name regex. Idt it's a bug but rather a user input issue.

**Comment by Ansel-Ch** [comment]
To add, you can try putting ur tg/ prefix behind any of the valid prefixes and u will see a message informing you about the incorrect input for that specific prefix.
