### ISSUE TITLE
[PE-D][Tester D] Assignments given to a Tutorial Group following after student is moved to new tutorial group

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-4/tp#286]
![image.png](https://raw.githubusercontent.com/jan-kai1/ped/main/files/14ff1309-051b-4ba2-8e61-fd494889def2.png)
Assignment Homework 2 assigned to G16 using `addatg`

Cal Moved to Z92 using `edits` and Assignment follows

![image.png](https://raw.githubusercontent.com/jan-kai1/ped/main/files/5472b0b8-f63f-46e1-b2ca-2e7108c78fdf.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: jan-kai1/ped#2

**Comment by Edsel-Tan** [comment]
Working as intended!
