### ISSUE TITLE
[PE-D][Tester D] Inaccurate Error message when dealing with unspecified flags

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-4/tp#293]
![image.png](https://raw.githubusercontent.com/jan-kai1/ped/main/files/096b76e8-4c68-4e81-b51c-0a2d6fd2170a.png)
Error message name should only contain alphanumeric characters

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jan-kai1/ped#3

**Comment by Ansel-Ch** [comment]
In this situation, the name of the student is "Bugman T/A21" and that contains a "/" character which is clearly not alphanumeric. Perhaps you could clarify what you mean by a non-useful message?
