### ISSUE TITLE
[PE-D][Tester C] Label for DG incorrect for view sequence diagram

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-4/tp#308]
![image.png](https://raw.githubusercontent.com/GuanpengR/ped/main/files/179c9ae9-2ad9-4ac2-bec8-0f5b69b3d57c.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: GuanpengR/ped#9

**Comment by Edsel-Tan** [comment]
Fixed. Thank you!
