### ISSUE TITLE
[PE-D][Tester E] Invalid Error Handling in Date 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-4/tp#345]
![image.png](https://raw.githubusercontent.com/taggyhan/ped/main/files/856c90de-59c5-47cd-b397-70e3c48b210b.png)

Error should be date does not exist --> not it is in the wrong format ( because it is still in YYYY-MM-DD) 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: taggyhan/ped#17

**Comment by natlv** [comment]
Thank you for pointing this out. We will be modifying the error message to handle this correctly.
