### ISSUE TITLE
[PE-D][Tester E] Date limits should be enforced

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T16-4/tp#346]
![image.png](https://raw.githubusercontent.com/taggyhan/ped/main/files/25b41f86-4799-455a-a005-3fc227ce3710.png)

![image.png](https://raw.githubusercontent.com/taggyhan/ped/main/files/18f70c3a-212b-4757-981f-5588e96981e2.png)

Obviously wrong dates should ideally throw an error

Future dates should be 100% be an error

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: taggyhan/ped#18

**Comment by natlv** [comment]
We will be allowing future dates. The rationale for this is that students may inform their tutor of their absence in advance. However, thank you for your effort in pointing this out.
